name: Basic Autonomi Network Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test-with-autonomi:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Start Autonomi Network
        id: start-network
        uses: maidsafe/autonomi-actions/spawn-autonomi-network@v1
        with:
          autonomi-version: 'stable-2025.7.1.3'
          node-count: '25'
          enable-evm: 'true'
      
      - name: Verify network is running
        run: |
          echo "Network Status: ${{ steps.start-network.outputs.network-status }}"
          echo "Peer Address: ${{ steps.start-network.outputs.peer-address }}"
          
          if [ "${{ steps.start-network.outputs.network-status }}" != "running" ]; then
            echo "❌ Network failed to start properly"
            exit 1
          fi
          
          echo "✅ Network is running successfully"
      
      - name: Run basic network tests
        run: |
          # Example: Test network connectivity and basic operations
          echo "Testing network with peer: $ANT_PEERS"
          echo "SECRET_KEY available: ${SECRET_KEY:+YES}${SECRET_KEY:-NO}"
          
          # Test basic ant CLI operations
          echo "Test file content" > test-file.txt
          
          # Upload file to network using --local flag
          ant --local file upload test-file.txt --public
          
          echo "✅ Basic tests completed"
      
      - name: Cleanup Autonomi Network
        if: always()
        uses: maidsafe/autonomi-actions/cleanup-autonomi-network@v1
        with:
          upload-logs: 'false'
          keep-directories: 'false'